
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: depot

test:
  <<: *default
  database: depot


production:
  <<: *default
  database: depot
  username: postgres
  password: <%= ENV['DEPOT_DATABASE_PASSWORD'] %>
